#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : opencv
Version  : 4.4.0
Release  : 133
URL      : https://github.com/opencv/opencv/archive/4.4.0/opencv-4.4.0.tar.gz
Source0  : https://github.com/opencv/opencv/archive/4.4.0/opencv-4.4.0.tar.gz
Summary  : Open Source Computer Vision Library
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 HPND IJG JasPer-2.0 LGPL-2.1 Libpng MIT libtiff
Requires: opencv-bin = %{version}-%{release}
Requires: opencv-data = %{version}-%{release}
Requires: opencv-lib = %{version}-%{release}
Requires: opencv-license = %{version}-%{release}
Requires: opencv-python = %{version}-%{release}
Requires: opencv-python3 = %{version}-%{release}
BuildRequires : VTK-dev
BuildRequires : ade-data
BuildRequires : ade-dev
BuildRequires : apache-ant
BuildRequires : beautifulsoup4
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : ccache
BuildRequires : cmake
BuildRequires : doxygen
BuildRequires : eigen-data
BuildRequires : eigen-dev
BuildRequires : gdal-dev
BuildRequires : glib-dev
BuildRequires : glibc-dev
BuildRequires : gstreamer-dev
BuildRequires : gtk3-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libgphoto2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : librealsense-dev
BuildRequires : libva-dev
BuildRequires : libva-intel-driver
BuildRequires : libwebp-dev
BuildRequires : mesa-dev
BuildRequires : numpy
BuildRequires : ocl-icd-dev
BuildRequires : openblas
BuildRequires : opencl-headers-dev
BuildRequires : opencv-dev
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : openjdk11-dev
BuildRequires : openjpeg
BuildRequires : pkg-config
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(libpng)
BuildRequires : protobuf-dev
BuildRequires : pugixml-dev
BuildRequires : python3-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : tbb-dev
BuildRequires : v4l-utils-dev
BuildRequires : zlib-dev

%description
A demo of the Java wrapper for OpenCV with two examples:
1) feature detection and matching and
2) face detection.
The examples are coded in Scala and Java.
Anyone familiar with Java should be able to read the Scala examples.
Please feel free to contribute code examples in Scala or Java, or any JVM language.

%package bin
Summary: bin components for the opencv package.
Group: Binaries
Requires: opencv-data = %{version}-%{release}
Requires: opencv-license = %{version}-%{release}

%description bin
bin components for the opencv package.


%package data
Summary: data components for the opencv package.
Group: Data

%description data
data components for the opencv package.


%package dev
Summary: dev components for the opencv package.
Group: Development
Requires: opencv-lib = %{version}-%{release}
Requires: opencv-bin = %{version}-%{release}
Requires: opencv-data = %{version}-%{release}
Provides: opencv-devel = %{version}-%{release}
Requires: opencv = %{version}-%{release}

%description dev
dev components for the opencv package.


%package extras-testing
Summary: extras-testing components for the opencv package.
Group: Default

%description extras-testing
extras-testing components for the opencv package.


%package lib
Summary: lib components for the opencv package.
Group: Libraries
Requires: opencv-data = %{version}-%{release}
Requires: opencv-license = %{version}-%{release}

%description lib
lib components for the opencv package.


%package license
Summary: license components for the opencv package.
Group: Default

%description license
license components for the opencv package.


%package python
Summary: python components for the opencv package.
Group: Default
Requires: opencv-python3 = %{version}-%{release}

%description python
python components for the opencv package.


%package python3
Summary: python3 components for the opencv package.
Group: Default
Requires: python3-core

%description python3
python3 components for the opencv package.


%prep
%setup -q -n opencv-4.4.0
cd %{_builddir}/opencv-4.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1623092954
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used "
export CFLAGS_GENERATE="$CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FCFLAGS_GENERATE="$FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FFLAGS_GENERATE="$FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CXXFLAGS_GENERATE="$CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export LDFLAGS_GENERATE="$LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CFLAGS_USE="$CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FCFLAGS_USE="$FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FFLAGS_USE="$FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export CXXFLAGS_USE="$CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export LDFLAGS_USE="$LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
%cmake .. -DCMAKE_INSTALL_LIBDIR:PATH=lib64 \
-DWITH_FFMPEG=Off \
-DWITH_1394=OFF \
-DWITH_GSTREAMER=ON \
-DWITH_IPP=OFF \
-DWITH_JASPER=OFF \
-DWITH_WEBP=ON \
-DWITH_OPENEXR=OFF \
-DWITH_TIFF=OFF \
-DENABLE_SSE42=ON \
-DWITH_TBB=ON \
-DWITH_OPENMP=ON \
-DWITH_VA=ON \
-DWITH_VULKAN=ON \
-DWITH_OPENJPEG=OFF \
-DCMAKE_BUILD_TYPE=ReleaseWithDebInfo \
-DWITH_GSTREAMER=1 \
-DINSTALL_PYTHON_EXAMPLES=1 \
-DCPU_DISPATCH=AVX,AVX2,AVX512_SKX \
-DLIB_SUFFIX= \
-DBUILD_EXAMPLES=ON \
-DBUILD_TESTS=ON \
-DBUILD_PERF_TESTS=ON \
-DINSTALL_TESTS=ON \
-DINSTALL_C_EXAMPLES=ON \
-DINSTALL_PYTHON_EXAMPLES=ON \
-DBUILD_JAVA=ON \
-DOPENCV_PYTHON_INSTALL_PATH=/usr/lib/python3.9/site-packages/ \
-DOPENCV_GENERATE_PKGCONFIG=ON \
-DOPENCV_CONFIG_INSTALL_PATH=lib64/cmake/opencv4
CFLAGS="${CFLAGS_GENERATE}" CXXFLAGS="${CXXFLAGS_GENERATE}" FFLAGS="${FFLAGS_GENERATE}" FCFLAGS="${FCFLAGS_GENERATE}" LDFLAGS="${LDFLAGS_GENERATE}"
make  %{?_smp_mflags}

bin/opencv_perf_core ||:
bin/opencv_perf_imgproc ||:
bin/opencv_perf_dnn ||:
bin/opencv_perf_stitching ||:
bin/opencv_perf_features2d ||:
bin/opencv_perf_superres ||:
make clean
CFLAGS="${CFLAGS_USE}" CXXFLAGS="${CXXFLAGS_USE}" FFLAGS="${FFLAGS_USE}" FCFLAGS="${FCFLAGS_USE}" LDFLAGS="${LDFLAGS_USE}"
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used -march=haswell "
export FCFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used -march=haswell "
export FFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used -march=haswell "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used -march=haswell "
export CFLAGS="$CFLAGS -march=haswell -m64"
export CXXFLAGS="$CXXFLAGS -march=haswell -m64"
export FFLAGS="$FFLAGS -march=haswell -m64"
export FCFLAGS="$FCFLAGS -march=haswell -m64"
%cmake .. -DCMAKE_INSTALL_LIBDIR:PATH=lib64 \
-DWITH_FFMPEG=Off \
-DWITH_1394=OFF \
-DWITH_GSTREAMER=ON \
-DWITH_IPP=OFF \
-DWITH_JASPER=OFF \
-DWITH_WEBP=ON \
-DWITH_OPENEXR=OFF \
-DWITH_TIFF=OFF \
-DENABLE_SSE42=ON \
-DWITH_TBB=ON \
-DWITH_OPENMP=ON \
-DWITH_VA=ON \
-DWITH_VULKAN=ON \
-DWITH_OPENJPEG=OFF \
-DCMAKE_BUILD_TYPE=ReleaseWithDebInfo \
-DWITH_GSTREAMER=1 \
-DINSTALL_PYTHON_EXAMPLES=1 \
-DCPU_DISPATCH=AVX,AVX2,AVX512_SKX \
-DLIB_SUFFIX= \
-DBUILD_EXAMPLES=ON \
-DBUILD_TESTS=ON \
-DBUILD_PERF_TESTS=ON \
-DINSTALL_TESTS=ON \
-DINSTALL_C_EXAMPLES=ON \
-DINSTALL_PYTHON_EXAMPLES=ON \
-DBUILD_JAVA=ON \
-DOPENCV_PYTHON_INSTALL_PATH=/usr/lib/python3.9/site-packages/ \
-DOPENCV_GENERATE_PKGCONFIG=ON \
-DOPENCV_CONFIG_INSTALL_PATH=lib64/cmake/opencv4
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx512
pushd clr-build-avx512
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used -march=skylake-avx512 "
export FCFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used -march=skylake-avx512 "
export FFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used -march=skylake-avx512 "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used -march=skylake-avx512 "
export CFLAGS_GENERATE="$CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FCFLAGS_GENERATE="$FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FFLAGS_GENERATE="$FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CXXFLAGS_GENERATE="$CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export LDFLAGS_GENERATE="$LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CFLAGS_USE="$CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FCFLAGS_USE="$FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FFLAGS_USE="$FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export CXXFLAGS_USE="$CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export LDFLAGS_USE="$LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export CFLAGS="$CFLAGS -march=skylake-avx512 -m64 "
export CXXFLAGS="$CXXFLAGS -march=skylake-avx512 -m64 "
export FFLAGS="$FFLAGS -march=skylake-avx512 -m64 "
export FCFLAGS="$FCFLAGS -march=skylake-avx512 -m64 "
%cmake .. -DCMAKE_INSTALL_LIBDIR:PATH=lib64 \
-DWITH_FFMPEG=Off \
-DWITH_1394=OFF \
-DWITH_GSTREAMER=ON \
-DWITH_IPP=OFF \
-DWITH_JASPER=OFF \
-DWITH_WEBP=ON \
-DWITH_OPENEXR=OFF \
-DWITH_TIFF=OFF \
-DENABLE_SSE42=ON \
-DWITH_TBB=ON \
-DWITH_OPENMP=ON \
-DWITH_VA=ON \
-DWITH_VULKAN=ON \
-DWITH_OPENJPEG=OFF \
-DCMAKE_BUILD_TYPE=ReleaseWithDebInfo \
-DWITH_GSTREAMER=1 \
-DINSTALL_PYTHON_EXAMPLES=1 \
-DCPU_DISPATCH=AVX,AVX2,AVX512_SKX \
-DLIB_SUFFIX= \
-DBUILD_EXAMPLES=ON \
-DBUILD_TESTS=ON \
-DBUILD_PERF_TESTS=ON \
-DINSTALL_TESTS=ON \
-DINSTALL_C_EXAMPLES=ON \
-DINSTALL_PYTHON_EXAMPLES=ON \
-DBUILD_JAVA=ON \
-DOPENCV_PYTHON_INSTALL_PATH=/usr/lib/python3.9/site-packages/ \
-DOPENCV_GENERATE_PKGCONFIG=ON \
-DOPENCV_CONFIG_INSTALL_PATH=lib64/cmake/opencv4
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1623092954
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/opencv
cp %{_builddir}/opencv-4.4.0/3rdparty/cpufeatures/LICENSE %{buildroot}/usr/share/package-licenses/opencv/ec4468ecfe59c46406d4fc5aca1cee2a83c4d93e
cp %{_builddir}/opencv-4.4.0/3rdparty/ffmpeg/license.txt %{buildroot}/usr/share/package-licenses/opencv/0aacebb8a54d52a40db8d2d449eceb42f66e198b
cp %{_builddir}/opencv-4.4.0/3rdparty/include/opencl/LICENSE.txt %{buildroot}/usr/share/package-licenses/opencv/7235f6784b4eae4c40a259dcecc7a20e6c487263
cp %{_builddir}/opencv-4.4.0/3rdparty/ittnotify/src/ittnotify/LICENSE.BSD %{buildroot}/usr/share/package-licenses/opencv/4f83a9480069279bc79a7af6990b9a546a1d0c02
cp %{_builddir}/opencv-4.4.0/3rdparty/ittnotify/src/ittnotify/LICENSE.GPL %{buildroot}/usr/share/package-licenses/opencv/49709bd29acf27e87953e37e63bb68373347a805
cp %{_builddir}/opencv-4.4.0/3rdparty/libjasper/LICENSE %{buildroot}/usr/share/package-licenses/opencv/14b5d0210560128e1a5d5204698cf705011ef792
cp %{_builddir}/opencv-4.4.0/3rdparty/libjasper/copyright %{buildroot}/usr/share/package-licenses/opencv/a6c8c1690157753de298c1ea2a66a2400d1ab5a3
cp %{_builddir}/opencv-4.4.0/3rdparty/libjpeg-turbo/LICENSE.md %{buildroot}/usr/share/package-licenses/opencv/a5f4d6f407de11b9ce0fef27e335ddcaeded9f2d
cp %{_builddir}/opencv-4.4.0/3rdparty/libpng/LICENSE %{buildroot}/usr/share/package-licenses/opencv/fc3951ba26fe1914759f605696a1d23e3b41766f
cp %{_builddir}/opencv-4.4.0/3rdparty/libtiff/COPYRIGHT %{buildroot}/usr/share/package-licenses/opencv/a2f64f2a85f5fd34bda8eb713c3aad008adbb589
cp %{_builddir}/opencv-4.4.0/3rdparty/libwebp/COPYING %{buildroot}/usr/share/package-licenses/opencv/59cd938fcbd6735b1ef91781280d6eb6c4b7c5d9
cp %{_builddir}/opencv-4.4.0/3rdparty/openexr/LICENSE %{buildroot}/usr/share/package-licenses/opencv/72f59fbac43fa1a7f0607d7fdba747832e626656
cp %{_builddir}/opencv-4.4.0/3rdparty/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/opencv/a0bcc878d7e7181b120ae51837c8d1703fe919ab
cp %{_builddir}/opencv-4.4.0/3rdparty/quirc/LICENSE %{buildroot}/usr/share/package-licenses/opencv/eaa22397809541edc6c7678716c4929f4977ee32
cp %{_builddir}/opencv-4.4.0/LICENSE %{buildroot}/usr/share/package-licenses/opencv/13afd4683100a8df1656137a1957db39e9f6f3bf
cp %{_builddir}/opencv-4.4.0/modules/core/3rdparty/SoftFloat/COPYING.txt %{buildroot}/usr/share/package-licenses/opencv/91a334a8403de4f677844cfcf4067720be0bb802
cp %{_builddir}/opencv-4.4.0/modules/dnn/src/torch/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/opencv/99d45ca0d503d7988a486e0d4f95058f89e14115
pushd clr-build-avx512
%make_install_avx512  || :
popd
pushd clr-build-avx2
%make_install_avx2  || :
popd
pushd clr-build
%make_install
popd
## install_append content
# A bad idea but this will allow things that use pkgconfig to use opencv4
# Probably remove at some point once software updates build detection for new upstream release
cp %{buildroot}/usr/lib64/pkgconfig/opencv4.pc %{buildroot}/usr/lib64/pkgconfig/opencv.pc
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/haswell/avx512_1/opencv_annotation
/usr/bin/haswell/avx512_1/opencv_interactive-calibration
/usr/bin/haswell/avx512_1/opencv_version
/usr/bin/haswell/avx512_1/opencv_visualisation
/usr/bin/haswell/opencv_annotation
/usr/bin/haswell/opencv_interactive-calibration
/usr/bin/haswell/opencv_version
/usr/bin/haswell/opencv_visualisation
/usr/bin/opencv_annotation
/usr/bin/opencv_interactive-calibration
/usr/bin/opencv_version
/usr/bin/opencv_visualisation
/usr/bin/setup_vars_opencv4.sh

%files data
%defattr(-,root,root,-)
/usr/share/licenses/opencv4/SoftFloat-COPYING.txt
/usr/share/licenses/opencv4/ittnotify-LICENSE.BSD
/usr/share/licenses/opencv4/ittnotify-LICENSE.GPL
/usr/share/licenses/opencv4/opencl-headers-LICENSE.txt
/usr/share/licenses/opencv4/protobuf-LICENSE
/usr/share/licenses/opencv4/protobuf-README.md
/usr/share/licenses/opencv4/quirc-LICENSE
/usr/share/opencv4/haarcascades/haarcascade_eye.xml
/usr/share/opencv4/haarcascades/haarcascade_eye_tree_eyeglasses.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalcatface.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalcatface_extended.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalface_alt.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalface_alt2.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalface_alt_tree.xml
/usr/share/opencv4/haarcascades/haarcascade_frontalface_default.xml
/usr/share/opencv4/haarcascades/haarcascade_fullbody.xml
/usr/share/opencv4/haarcascades/haarcascade_lefteye_2splits.xml
/usr/share/opencv4/haarcascades/haarcascade_licence_plate_rus_16stages.xml
/usr/share/opencv4/haarcascades/haarcascade_lowerbody.xml
/usr/share/opencv4/haarcascades/haarcascade_profileface.xml
/usr/share/opencv4/haarcascades/haarcascade_righteye_2splits.xml
/usr/share/opencv4/haarcascades/haarcascade_russian_plate_number.xml
/usr/share/opencv4/haarcascades/haarcascade_smile.xml
/usr/share/opencv4/haarcascades/haarcascade_upperbody.xml
/usr/share/opencv4/lbpcascades/lbpcascade_frontalcatface.xml
/usr/share/opencv4/lbpcascades/lbpcascade_frontalface.xml
/usr/share/opencv4/lbpcascades/lbpcascade_frontalface_improved.xml
/usr/share/opencv4/lbpcascades/lbpcascade_profileface.xml
/usr/share/opencv4/lbpcascades/lbpcascade_silverware.xml
/usr/share/opencv4/samples/CMakeLists.txt
/usr/share/opencv4/samples/cpp/3calibration.cpp
/usr/share/opencv4/samples/cpp/CMakeLists.txt
/usr/share/opencv4/samples/cpp/application_trace.cpp
/usr/share/opencv4/samples/cpp/bgfg_segm.cpp
/usr/share/opencv4/samples/cpp/calibration.cpp
/usr/share/opencv4/samples/cpp/camshiftdemo.cpp
/usr/share/opencv4/samples/cpp/cloning_demo.cpp
/usr/share/opencv4/samples/cpp/cloning_gui.cpp
/usr/share/opencv4/samples/cpp/connected_components.cpp
/usr/share/opencv4/samples/cpp/contours2.cpp
/usr/share/opencv4/samples/cpp/convexhull.cpp
/usr/share/opencv4/samples/cpp/cout_mat.cpp
/usr/share/opencv4/samples/cpp/create_mask.cpp
/usr/share/opencv4/samples/cpp/dbt_face_detection.cpp
/usr/share/opencv4/samples/cpp/delaunay2.cpp
/usr/share/opencv4/samples/cpp/demhist.cpp
/usr/share/opencv4/samples/cpp/detect_blob.cpp
/usr/share/opencv4/samples/cpp/detect_mser.cpp
/usr/share/opencv4/samples/cpp/dft.cpp
/usr/share/opencv4/samples/cpp/digits.cpp
/usr/share/opencv4/samples/cpp/dis_opticalflow.cpp
/usr/share/opencv4/samples/cpp/distrans.cpp
/usr/share/opencv4/samples/cpp/drawing.cpp
/usr/share/opencv4/samples/cpp/edge.cpp
/usr/share/opencv4/samples/cpp/ela.cpp
/usr/share/opencv4/samples/cpp/em.cpp
/usr/share/opencv4/samples/cpp/facedetect.cpp
/usr/share/opencv4/samples/cpp/facial_features.cpp
/usr/share/opencv4/samples/cpp/falsecolor.cpp
/usr/share/opencv4/samples/cpp/fback.cpp
/usr/share/opencv4/samples/cpp/ffilldemo.cpp
/usr/share/opencv4/samples/cpp/filestorage.cpp
/usr/share/opencv4/samples/cpp/fitellipse.cpp
/usr/share/opencv4/samples/cpp/grabcut.cpp
/usr/share/opencv4/samples/cpp/image_alignment.cpp
/usr/share/opencv4/samples/cpp/imagelist_creator.cpp
/usr/share/opencv4/samples/cpp/imagelist_reader.cpp
/usr/share/opencv4/samples/cpp/inpaint.cpp
/usr/share/opencv4/samples/cpp/intelligent_scissors.cpp
/usr/share/opencv4/samples/cpp/intersectExample.cpp
/usr/share/opencv4/samples/cpp/kalman.cpp
/usr/share/opencv4/samples/cpp/kmeans.cpp
/usr/share/opencv4/samples/cpp/laplace.cpp
/usr/share/opencv4/samples/cpp/letter_recog.cpp
/usr/share/opencv4/samples/cpp/lkdemo.cpp
/usr/share/opencv4/samples/cpp/logistic_regression.cpp
/usr/share/opencv4/samples/cpp/mask_tmpl.cpp
/usr/share/opencv4/samples/cpp/matchmethod_orb_akaze_brisk.cpp
/usr/share/opencv4/samples/cpp/minarea.cpp
/usr/share/opencv4/samples/cpp/morphology2.cpp
/usr/share/opencv4/samples/cpp/neural_network.cpp
/usr/share/opencv4/samples/cpp/npr_demo.cpp
/usr/share/opencv4/samples/cpp/opencv_version.cpp
/usr/share/opencv4/samples/cpp/pca.cpp
/usr/share/opencv4/samples/cpp/peopledetect.cpp
/usr/share/opencv4/samples/cpp/phase_corr.cpp
/usr/share/opencv4/samples/cpp/points_classifier.cpp
/usr/share/opencv4/samples/cpp/polar_transforms.cpp
/usr/share/opencv4/samples/cpp/qrcode.cpp
/usr/share/opencv4/samples/cpp/segment_objects.cpp
/usr/share/opencv4/samples/cpp/select3dobj.cpp
/usr/share/opencv4/samples/cpp/simd_basic.cpp
/usr/share/opencv4/samples/cpp/smiledetect.cpp
/usr/share/opencv4/samples/cpp/squares.cpp
/usr/share/opencv4/samples/cpp/stereo_calib.cpp
/usr/share/opencv4/samples/cpp/stereo_match.cpp
/usr/share/opencv4/samples/cpp/stitching.cpp
/usr/share/opencv4/samples/cpp/stitching_detailed.cpp
/usr/share/opencv4/samples/cpp/text_skewness_correction.cpp
/usr/share/opencv4/samples/cpp/train_HOG.cpp
/usr/share/opencv4/samples/cpp/train_svmsgd.cpp
/usr/share/opencv4/samples/cpp/travelsalesman.cpp
/usr/share/opencv4/samples/cpp/tree_engine.cpp
/usr/share/opencv4/samples/cpp/videocapture_basic.cpp
/usr/share/opencv4/samples/cpp/videocapture_camera.cpp
/usr/share/opencv4/samples/cpp/videocapture_gphoto2_autofocus.cpp
/usr/share/opencv4/samples/cpp/videocapture_gstreamer_pipeline.cpp
/usr/share/opencv4/samples/cpp/videocapture_image_sequence.cpp
/usr/share/opencv4/samples/cpp/videocapture_intelperc.cpp
/usr/share/opencv4/samples/cpp/videocapture_openni.cpp
/usr/share/opencv4/samples/cpp/videocapture_starter.cpp
/usr/share/opencv4/samples/cpp/videowriter_basic.cpp
/usr/share/opencv4/samples/cpp/warpPerspective_demo.cpp
/usr/share/opencv4/samples/cpp/watershed.cpp
/usr/share/opencv4/samples/data/Blender_Suzanne1.jpg
/usr/share/opencv4/samples/data/Blender_Suzanne2.jpg
/usr/share/opencv4/samples/data/H1to3p.xml
/usr/share/opencv4/samples/data/HappyFish.jpg
/usr/share/opencv4/samples/data/LinuxLogo.jpg
/usr/share/opencv4/samples/data/Megamind.avi
/usr/share/opencv4/samples/data/Megamind_bugy.avi
/usr/share/opencv4/samples/data/WindowsLogo.jpg
/usr/share/opencv4/samples/data/aero1.jpg
/usr/share/opencv4/samples/data/aero3.jpg
/usr/share/opencv4/samples/data/aloeGT.png
/usr/share/opencv4/samples/data/aloeL.jpg
/usr/share/opencv4/samples/data/aloeR.jpg
/usr/share/opencv4/samples/data/apple.jpg
/usr/share/opencv4/samples/data/baboon.jpg
/usr/share/opencv4/samples/data/basketball1.png
/usr/share/opencv4/samples/data/basketball2.png
/usr/share/opencv4/samples/data/blox.jpg
/usr/share/opencv4/samples/data/board.jpg
/usr/share/opencv4/samples/data/box.png
/usr/share/opencv4/samples/data/box_in_scene.png
/usr/share/opencv4/samples/data/building.jpg
/usr/share/opencv4/samples/data/butterfly.jpg
/usr/share/opencv4/samples/data/calibration.yml
/usr/share/opencv4/samples/data/cards.png
/usr/share/opencv4/samples/data/chessboard.png
/usr/share/opencv4/samples/data/chicky_512.png
/usr/share/opencv4/samples/data/data01.xml
/usr/share/opencv4/samples/data/detect_blob.png
/usr/share/opencv4/samples/data/digits.png
/usr/share/opencv4/samples/data/dnn/action_recongnition_kinetics.txt
/usr/share/opencv4/samples/data/dnn/classification_classes_ILSVRC2012.txt
/usr/share/opencv4/samples/data/dnn/enet-classes.txt
/usr/share/opencv4/samples/data/dnn/object_detection_classes_coco.txt
/usr/share/opencv4/samples/data/dnn/object_detection_classes_pascal_voc.txt
/usr/share/opencv4/samples/data/dnn/object_detection_classes_yolov3.txt
/usr/share/opencv4/samples/data/ela_modified.jpg
/usr/share/opencv4/samples/data/ela_original.jpg
/usr/share/opencv4/samples/data/ellipses.jpg
/usr/share/opencv4/samples/data/fruits.jpg
/usr/share/opencv4/samples/data/gradient.png
/usr/share/opencv4/samples/data/graf1.png
/usr/share/opencv4/samples/data/graf3.png
/usr/share/opencv4/samples/data/home.jpg
/usr/share/opencv4/samples/data/imageTextN.png
/usr/share/opencv4/samples/data/imageTextR.png
/usr/share/opencv4/samples/data/intrinsics.yml
/usr/share/opencv4/samples/data/left.jpg
/usr/share/opencv4/samples/data/left01.jpg
/usr/share/opencv4/samples/data/left02.jpg
/usr/share/opencv4/samples/data/left03.jpg
/usr/share/opencv4/samples/data/left04.jpg
/usr/share/opencv4/samples/data/left05.jpg
/usr/share/opencv4/samples/data/left06.jpg
/usr/share/opencv4/samples/data/left07.jpg
/usr/share/opencv4/samples/data/left08.jpg
/usr/share/opencv4/samples/data/left09.jpg
/usr/share/opencv4/samples/data/left11.jpg
/usr/share/opencv4/samples/data/left12.jpg
/usr/share/opencv4/samples/data/left13.jpg
/usr/share/opencv4/samples/data/left14.jpg
/usr/share/opencv4/samples/data/left_intrinsics.yml
/usr/share/opencv4/samples/data/lena.jpg
/usr/share/opencv4/samples/data/lena_tmpl.jpg
/usr/share/opencv4/samples/data/letter-recognition.data
/usr/share/opencv4/samples/data/licenseplate_motion.jpg
/usr/share/opencv4/samples/data/mask.png
/usr/share/opencv4/samples/data/messi5.jpg
/usr/share/opencv4/samples/data/ml.png
/usr/share/opencv4/samples/data/notes.png
/usr/share/opencv4/samples/data/opencv-logo-white.png
/usr/share/opencv4/samples/data/opencv-logo.png
/usr/share/opencv4/samples/data/orange.jpg
/usr/share/opencv4/samples/data/pca_test1.jpg
/usr/share/opencv4/samples/data/pic1.png
/usr/share/opencv4/samples/data/pic2.png
/usr/share/opencv4/samples/data/pic3.png
/usr/share/opencv4/samples/data/pic4.png
/usr/share/opencv4/samples/data/pic5.png
/usr/share/opencv4/samples/data/pic6.png
/usr/share/opencv4/samples/data/right.jpg
/usr/share/opencv4/samples/data/right01.jpg
/usr/share/opencv4/samples/data/right02.jpg
/usr/share/opencv4/samples/data/right03.jpg
/usr/share/opencv4/samples/data/right04.jpg
/usr/share/opencv4/samples/data/right05.jpg
/usr/share/opencv4/samples/data/right06.jpg
/usr/share/opencv4/samples/data/right07.jpg
/usr/share/opencv4/samples/data/right08.jpg
/usr/share/opencv4/samples/data/right09.jpg
/usr/share/opencv4/samples/data/right11.jpg
/usr/share/opencv4/samples/data/right12.jpg
/usr/share/opencv4/samples/data/right13.jpg
/usr/share/opencv4/samples/data/right14.jpg
/usr/share/opencv4/samples/data/rubberwhale1.png
/usr/share/opencv4/samples/data/rubberwhale2.png
/usr/share/opencv4/samples/data/smarties.png
/usr/share/opencv4/samples/data/starry_night.jpg
/usr/share/opencv4/samples/data/stereo_calib.xml
/usr/share/opencv4/samples/data/stuff.jpg
/usr/share/opencv4/samples/data/sudoku.png
/usr/share/opencv4/samples/data/templ.png
/usr/share/opencv4/samples/data/text_defocus.jpg
/usr/share/opencv4/samples/data/text_motion.jpg
/usr/share/opencv4/samples/data/tmpl.png
/usr/share/opencv4/samples/data/tree.avi
/usr/share/opencv4/samples/data/vtest.avi
/usr/share/opencv4/samples/dnn/CMakeLists.txt
/usr/share/opencv4/samples/dnn/classification.cpp
/usr/share/opencv4/samples/dnn/colorization.cpp
/usr/share/opencv4/samples/dnn/common.hpp
/usr/share/opencv4/samples/dnn/custom_layers.hpp
/usr/share/opencv4/samples/dnn/human_parsing.cpp
/usr/share/opencv4/samples/dnn/object_detection.cpp
/usr/share/opencv4/samples/dnn/openpose.cpp
/usr/share/opencv4/samples/dnn/segmentation.cpp
/usr/share/opencv4/samples/dnn/text_detection.cpp
/usr/share/opencv4/samples/gpu/CMakeLists.txt
/usr/share/opencv4/samples/gpu/alpha_comp.cpp
/usr/share/opencv4/samples/gpu/bgfg_segm.cpp
/usr/share/opencv4/samples/gpu/cascadeclassifier.cpp
/usr/share/opencv4/samples/gpu/farneback_optical_flow.cpp
/usr/share/opencv4/samples/gpu/generalized_hough.cpp
/usr/share/opencv4/samples/gpu/hog.cpp
/usr/share/opencv4/samples/gpu/houghlines.cpp
/usr/share/opencv4/samples/gpu/morphology.cpp
/usr/share/opencv4/samples/gpu/multi.cpp
/usr/share/opencv4/samples/gpu/pyrlk_optical_flow.cpp
/usr/share/opencv4/samples/gpu/stereo_match.cpp
/usr/share/opencv4/samples/gpu/stereo_multi.cpp
/usr/share/opencv4/samples/gpu/super_resolution.cpp
/usr/share/opencv4/samples/gpu/surf_keypoint_matcher.cpp
/usr/share/opencv4/samples/gpu/video_reader.cpp
/usr/share/opencv4/samples/gpu/video_writer.cpp
/usr/share/opencv4/samples/opencl/CMakeLists.txt
/usr/share/opencv4/samples/opencl/display.cpp.inc
/usr/share/opencv4/samples/opencl/opencl-opencv-interop.cpp
/usr/share/opencv4/samples/opencl/va_intel_interop.cpp
/usr/share/opencv4/samples/python/_coverage.py
/usr/share/opencv4/samples/python/_doc.py
/usr/share/opencv4/samples/python/asift.py
/usr/share/opencv4/samples/python/browse.py
/usr/share/opencv4/samples/python/calibrate.py
/usr/share/opencv4/samples/python/camera_calibration_show_extrinsics.py
/usr/share/opencv4/samples/python/camshift.py
/usr/share/opencv4/samples/python/coherence.py
/usr/share/opencv4/samples/python/color_histogram.py
/usr/share/opencv4/samples/python/common.py
/usr/share/opencv4/samples/python/contours.py
/usr/share/opencv4/samples/python/deconvolution.py
/usr/share/opencv4/samples/python/demo.py
/usr/share/opencv4/samples/python/dft.py
/usr/share/opencv4/samples/python/digits.py
/usr/share/opencv4/samples/python/digits_adjust.py
/usr/share/opencv4/samples/python/digits_video.py
/usr/share/opencv4/samples/python/dis_opt_flow.py
/usr/share/opencv4/samples/python/distrans.py
/usr/share/opencv4/samples/python/drawing.py
/usr/share/opencv4/samples/python/edge.py
/usr/share/opencv4/samples/python/facedetect.py
/usr/share/opencv4/samples/python/feature_homography.py
/usr/share/opencv4/samples/python/find_obj.py
/usr/share/opencv4/samples/python/fitline.py
/usr/share/opencv4/samples/python/floodfill.py
/usr/share/opencv4/samples/python/gabor_threads.py
/usr/share/opencv4/samples/python/gaussian_mix.py
/usr/share/opencv4/samples/python/grabcut.py
/usr/share/opencv4/samples/python/hist.py
/usr/share/opencv4/samples/python/houghcircles.py
/usr/share/opencv4/samples/python/houghlines.py
/usr/share/opencv4/samples/python/inpaint.py
/usr/share/opencv4/samples/python/kalman.py
/usr/share/opencv4/samples/python/kmeans.py
/usr/share/opencv4/samples/python/laplace.py
/usr/share/opencv4/samples/python/lappyr.py
/usr/share/opencv4/samples/python/letter_recog.py
/usr/share/opencv4/samples/python/lk_homography.py
/usr/share/opencv4/samples/python/lk_track.py
/usr/share/opencv4/samples/python/logpolar.py
/usr/share/opencv4/samples/python/morphology.py
/usr/share/opencv4/samples/python/mosse.py
/usr/share/opencv4/samples/python/mouse_and_match.py
/usr/share/opencv4/samples/python/mser.py
/usr/share/opencv4/samples/python/opencv_version.py
/usr/share/opencv4/samples/python/opt_flow.py
/usr/share/opencv4/samples/python/peopledetect.py
/usr/share/opencv4/samples/python/plane_ar.py
/usr/share/opencv4/samples/python/plane_tracker.py
/usr/share/opencv4/samples/python/qrcode.py
/usr/share/opencv4/samples/python/squares.py
/usr/share/opencv4/samples/python/stereo_match.py
/usr/share/opencv4/samples/python/stitching.py
/usr/share/opencv4/samples/python/stitching_detailed.py
/usr/share/opencv4/samples/python/text_skewness_correction.py
/usr/share/opencv4/samples/python/texture_flow.py
/usr/share/opencv4/samples/python/tst_scene_render.py
/usr/share/opencv4/samples/python/turing.py
/usr/share/opencv4/samples/python/video.py
/usr/share/opencv4/samples/python/video_threaded.py
/usr/share/opencv4/samples/python/video_v4l2.py
/usr/share/opencv4/samples/python/watershed.py
/usr/share/opencv4/samples/samples_utils.cmake
/usr/share/opencv4/samples/tapi/CMakeLists.txt
/usr/share/opencv4/samples/tapi/bgfg_segm.cpp
/usr/share/opencv4/samples/tapi/camshift.cpp
/usr/share/opencv4/samples/tapi/clahe.cpp
/usr/share/opencv4/samples/tapi/dense_optical_flow.cpp
/usr/share/opencv4/samples/tapi/hog.cpp
/usr/share/opencv4/samples/tapi/opencl_custom_kernel.cpp
/usr/share/opencv4/samples/tapi/pyrlk_optical_flow.cpp
/usr/share/opencv4/samples/tapi/squares.cpp
/usr/share/opencv4/samples/tapi/ufacedetect.cpp
/usr/share/opencv4/valgrind.supp
/usr/share/opencv4/valgrind_3rdparty.supp

%files dev
%defattr(-,root,root,-)
/usr/include/opencv4/opencv2/calib3d.hpp
/usr/include/opencv4/opencv2/calib3d/calib3d.hpp
/usr/include/opencv4/opencv2/calib3d/calib3d_c.h
/usr/include/opencv4/opencv2/core.hpp
/usr/include/opencv4/opencv2/core/affine.hpp
/usr/include/opencv4/opencv2/core/async.hpp
/usr/include/opencv4/opencv2/core/base.hpp
/usr/include/opencv4/opencv2/core/bindings_utils.hpp
/usr/include/opencv4/opencv2/core/bufferpool.hpp
/usr/include/opencv4/opencv2/core/check.hpp
/usr/include/opencv4/opencv2/core/core.hpp
/usr/include/opencv4/opencv2/core/core_c.h
/usr/include/opencv4/opencv2/core/cuda.hpp
/usr/include/opencv4/opencv2/core/cuda.inl.hpp
/usr/include/opencv4/opencv2/core/cuda/block.hpp
/usr/include/opencv4/opencv2/core/cuda/border_interpolate.hpp
/usr/include/opencv4/opencv2/core/cuda/color.hpp
/usr/include/opencv4/opencv2/core/cuda/common.hpp
/usr/include/opencv4/opencv2/core/cuda/datamov_utils.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/color_detail.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/reduce.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/reduce_key_val.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/transform_detail.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/type_traits_detail.hpp
/usr/include/opencv4/opencv2/core/cuda/detail/vec_distance_detail.hpp
/usr/include/opencv4/opencv2/core/cuda/dynamic_smem.hpp
/usr/include/opencv4/opencv2/core/cuda/emulation.hpp
/usr/include/opencv4/opencv2/core/cuda/filters.hpp
/usr/include/opencv4/opencv2/core/cuda/funcattrib.hpp
/usr/include/opencv4/opencv2/core/cuda/functional.hpp
/usr/include/opencv4/opencv2/core/cuda/limits.hpp
/usr/include/opencv4/opencv2/core/cuda/reduce.hpp
/usr/include/opencv4/opencv2/core/cuda/saturate_cast.hpp
/usr/include/opencv4/opencv2/core/cuda/scan.hpp
/usr/include/opencv4/opencv2/core/cuda/simd_functions.hpp
/usr/include/opencv4/opencv2/core/cuda/transform.hpp
/usr/include/opencv4/opencv2/core/cuda/type_traits.hpp
/usr/include/opencv4/opencv2/core/cuda/utility.hpp
/usr/include/opencv4/opencv2/core/cuda/vec_distance.hpp
/usr/include/opencv4/opencv2/core/cuda/vec_math.hpp
/usr/include/opencv4/opencv2/core/cuda/vec_traits.hpp
/usr/include/opencv4/opencv2/core/cuda/warp.hpp
/usr/include/opencv4/opencv2/core/cuda/warp_reduce.hpp
/usr/include/opencv4/opencv2/core/cuda/warp_shuffle.hpp
/usr/include/opencv4/opencv2/core/cuda_stream_accessor.hpp
/usr/include/opencv4/opencv2/core/cuda_types.hpp
/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h
/usr/include/opencv4/opencv2/core/cv_cpu_helper.h
/usr/include/opencv4/opencv2/core/cvdef.h
/usr/include/opencv4/opencv2/core/cvstd.hpp
/usr/include/opencv4/opencv2/core/cvstd.inl.hpp
/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp
/usr/include/opencv4/opencv2/core/detail/async_promise.hpp
/usr/include/opencv4/opencv2/core/detail/exception_ptr.hpp
/usr/include/opencv4/opencv2/core/directx.hpp
/usr/include/opencv4/opencv2/core/eigen.hpp
/usr/include/opencv4/opencv2/core/fast_math.hpp
/usr/include/opencv4/opencv2/core/hal/hal.hpp
/usr/include/opencv4/opencv2/core/hal/interface.h
/usr/include/opencv4/opencv2/core/hal/intrin.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_avx.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_avx512.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_cpp.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_forward.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_msa.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_neon.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_sse.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_sse_em.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_vsx.hpp
/usr/include/opencv4/opencv2/core/hal/intrin_wasm.hpp
/usr/include/opencv4/opencv2/core/hal/msa_macros.h
/usr/include/opencv4/opencv2/core/hal/simd_utils.impl.hpp
/usr/include/opencv4/opencv2/core/mat.hpp
/usr/include/opencv4/opencv2/core/mat.inl.hpp
/usr/include/opencv4/opencv2/core/matx.hpp
/usr/include/opencv4/opencv2/core/neon_utils.hpp
/usr/include/opencv4/opencv2/core/ocl.hpp
/usr/include/opencv4/opencv2/core/ocl_genbase.hpp
/usr/include/opencv4/opencv2/core/opencl/ocl_defs.hpp
/usr/include/opencv4/opencv2/core/opencl/opencl_info.hpp
/usr/include/opencv4/opencv2/core/opencl/opencl_svm.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_clamdblas.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_clamdfft.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_core_wrappers.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_clamdblas.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_clamdfft.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_core.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_gl.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_gl_wrappers.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_20.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_definitions.hpp
/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_hsa_extension.hpp
/usr/include/opencv4/opencv2/core/opengl.hpp
/usr/include/opencv4/opencv2/core/operations.hpp
/usr/include/opencv4/opencv2/core/optim.hpp
/usr/include/opencv4/opencv2/core/ovx.hpp
/usr/include/opencv4/opencv2/core/persistence.hpp
/usr/include/opencv4/opencv2/core/saturate.hpp
/usr/include/opencv4/opencv2/core/simd_intrinsics.hpp
/usr/include/opencv4/opencv2/core/softfloat.hpp
/usr/include/opencv4/opencv2/core/sse_utils.hpp
/usr/include/opencv4/opencv2/core/traits.hpp
/usr/include/opencv4/opencv2/core/types.hpp
/usr/include/opencv4/opencv2/core/types_c.h
/usr/include/opencv4/opencv2/core/utility.hpp
/usr/include/opencv4/opencv2/core/utils/allocator_stats.hpp
/usr/include/opencv4/opencv2/core/utils/allocator_stats.impl.hpp
/usr/include/opencv4/opencv2/core/utils/filesystem.hpp
/usr/include/opencv4/opencv2/core/utils/instrumentation.hpp
/usr/include/opencv4/opencv2/core/utils/logger.defines.hpp
/usr/include/opencv4/opencv2/core/utils/logger.hpp
/usr/include/opencv4/opencv2/core/utils/logtag.hpp
/usr/include/opencv4/opencv2/core/utils/tls.hpp
/usr/include/opencv4/opencv2/core/utils/trace.hpp
/usr/include/opencv4/opencv2/core/va_intel.hpp
/usr/include/opencv4/opencv2/core/version.hpp
/usr/include/opencv4/opencv2/core/vsx_utils.hpp
/usr/include/opencv4/opencv2/cvconfig.h
/usr/include/opencv4/opencv2/dnn.hpp
/usr/include/opencv4/opencv2/dnn/all_layers.hpp
/usr/include/opencv4/opencv2/dnn/dict.hpp
/usr/include/opencv4/opencv2/dnn/dnn.hpp
/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp
/usr/include/opencv4/opencv2/dnn/layer.details.hpp
/usr/include/opencv4/opencv2/dnn/layer.hpp
/usr/include/opencv4/opencv2/dnn/shape_utils.hpp
/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp
/usr/include/opencv4/opencv2/dnn/version.hpp
/usr/include/opencv4/opencv2/features2d.hpp
/usr/include/opencv4/opencv2/features2d/features2d.hpp
/usr/include/opencv4/opencv2/features2d/hal/interface.h
/usr/include/opencv4/opencv2/flann.hpp
/usr/include/opencv4/opencv2/flann/all_indices.h
/usr/include/opencv4/opencv2/flann/allocator.h
/usr/include/opencv4/opencv2/flann/any.h
/usr/include/opencv4/opencv2/flann/autotuned_index.h
/usr/include/opencv4/opencv2/flann/composite_index.h
/usr/include/opencv4/opencv2/flann/config.h
/usr/include/opencv4/opencv2/flann/defines.h
/usr/include/opencv4/opencv2/flann/dist.h
/usr/include/opencv4/opencv2/flann/dummy.h
/usr/include/opencv4/opencv2/flann/dynamic_bitset.h
/usr/include/opencv4/opencv2/flann/flann.hpp
/usr/include/opencv4/opencv2/flann/flann_base.hpp
/usr/include/opencv4/opencv2/flann/general.h
/usr/include/opencv4/opencv2/flann/ground_truth.h
/usr/include/opencv4/opencv2/flann/hdf5.h
/usr/include/opencv4/opencv2/flann/heap.h
/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h
/usr/include/opencv4/opencv2/flann/index_testing.h
/usr/include/opencv4/opencv2/flann/kdtree_index.h
/usr/include/opencv4/opencv2/flann/kdtree_single_index.h
/usr/include/opencv4/opencv2/flann/kmeans_index.h
/usr/include/opencv4/opencv2/flann/linear_index.h
/usr/include/opencv4/opencv2/flann/logger.h
/usr/include/opencv4/opencv2/flann/lsh_index.h
/usr/include/opencv4/opencv2/flann/lsh_table.h
/usr/include/opencv4/opencv2/flann/matrix.h
/usr/include/opencv4/opencv2/flann/miniflann.hpp
/usr/include/opencv4/opencv2/flann/nn_index.h
/usr/include/opencv4/opencv2/flann/object_factory.h
/usr/include/opencv4/opencv2/flann/params.h
/usr/include/opencv4/opencv2/flann/random.h
/usr/include/opencv4/opencv2/flann/result_set.h
/usr/include/opencv4/opencv2/flann/sampling.h
/usr/include/opencv4/opencv2/flann/saving.h
/usr/include/opencv4/opencv2/flann/simplex_downhill.h
/usr/include/opencv4/opencv2/flann/timer.h
/usr/include/opencv4/opencv2/highgui.hpp
/usr/include/opencv4/opencv2/highgui/highgui.hpp
/usr/include/opencv4/opencv2/highgui/highgui_c.h
/usr/include/opencv4/opencv2/imgcodecs.hpp
/usr/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp
/usr/include/opencv4/opencv2/imgcodecs/imgcodecs_c.h
/usr/include/opencv4/opencv2/imgcodecs/ios.h
/usr/include/opencv4/opencv2/imgcodecs/legacy/constants_c.h
/usr/include/opencv4/opencv2/imgproc.hpp
/usr/include/opencv4/opencv2/imgproc/detail/gcgraph.hpp
/usr/include/opencv4/opencv2/imgproc/hal/hal.hpp
/usr/include/opencv4/opencv2/imgproc/hal/interface.h
/usr/include/opencv4/opencv2/imgproc/imgproc.hpp
/usr/include/opencv4/opencv2/imgproc/imgproc_c.h
/usr/include/opencv4/opencv2/imgproc/types_c.h
/usr/include/opencv4/opencv2/ml.hpp
/usr/include/opencv4/opencv2/ml/ml.hpp
/usr/include/opencv4/opencv2/ml/ml.inl.hpp
/usr/include/opencv4/opencv2/objdetect.hpp
/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp
/usr/include/opencv4/opencv2/objdetect/objdetect.hpp
/usr/include/opencv4/opencv2/opencv.hpp
/usr/include/opencv4/opencv2/opencv_modules.hpp
/usr/include/opencv4/opencv2/photo.hpp
/usr/include/opencv4/opencv2/photo/cuda.hpp
/usr/include/opencv4/opencv2/photo/legacy/constants_c.h
/usr/include/opencv4/opencv2/photo/photo.hpp
/usr/include/opencv4/opencv2/stitching.hpp
/usr/include/opencv4/opencv2/stitching/detail/autocalib.hpp
/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp
/usr/include/opencv4/opencv2/stitching/detail/camera.hpp
/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp
/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp
/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp
/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp
/usr/include/opencv4/opencv2/stitching/detail/timelapsers.hpp
/usr/include/opencv4/opencv2/stitching/detail/util.hpp
/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp
/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp
/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp
/usr/include/opencv4/opencv2/stitching/warpers.hpp
/usr/include/opencv4/opencv2/video.hpp
/usr/include/opencv4/opencv2/video/background_segm.hpp
/usr/include/opencv4/opencv2/video/legacy/constants_c.h
/usr/include/opencv4/opencv2/video/tracking.hpp
/usr/include/opencv4/opencv2/video/video.hpp
/usr/include/opencv4/opencv2/videoio.hpp
/usr/include/opencv4/opencv2/videoio/cap_ios.h
/usr/include/opencv4/opencv2/videoio/legacy/constants_c.h
/usr/include/opencv4/opencv2/videoio/registry.hpp
/usr/include/opencv4/opencv2/videoio/videoio.hpp
/usr/include/opencv4/opencv2/videoio/videoio_c.h
/usr/lib64/cmake/opencv4/OpenCVConfig-version.cmake
/usr/lib64/cmake/opencv4/OpenCVConfig.cmake
/usr/lib64/cmake/opencv4/OpenCVModules-releasewithdebinfo.cmake
/usr/lib64/cmake/opencv4/OpenCVModules.cmake
/usr/lib64/haswell/avx512_1/libopencv_calib3d.so
/usr/lib64/haswell/avx512_1/libopencv_core.so
/usr/lib64/haswell/avx512_1/libopencv_dnn.so
/usr/lib64/haswell/avx512_1/libopencv_features2d.so
/usr/lib64/haswell/avx512_1/libopencv_flann.so
/usr/lib64/haswell/avx512_1/libopencv_imgcodecs.so
/usr/lib64/haswell/avx512_1/libopencv_imgproc.so
/usr/lib64/haswell/avx512_1/libopencv_ml.so
/usr/lib64/haswell/avx512_1/libopencv_objdetect.so
/usr/lib64/haswell/avx512_1/libopencv_photo.so
/usr/lib64/haswell/avx512_1/libopencv_stitching.so
/usr/lib64/haswell/avx512_1/libopencv_video.so
/usr/lib64/haswell/avx512_1/libopencv_videoio.so
/usr/lib64/haswell/libopencv_calib3d.so
/usr/lib64/haswell/libopencv_core.so
/usr/lib64/haswell/libopencv_dnn.so
/usr/lib64/haswell/libopencv_features2d.so
/usr/lib64/haswell/libopencv_flann.so
/usr/lib64/haswell/libopencv_highgui.so
/usr/lib64/haswell/libopencv_imgcodecs.so
/usr/lib64/haswell/libopencv_imgproc.so
/usr/lib64/haswell/libopencv_ml.so
/usr/lib64/haswell/libopencv_objdetect.so
/usr/lib64/haswell/libopencv_photo.so
/usr/lib64/haswell/libopencv_stitching.so
/usr/lib64/haswell/libopencv_video.so
/usr/lib64/haswell/libopencv_videoio.so
/usr/lib64/libopencv_calib3d.so
/usr/lib64/libopencv_core.so
/usr/lib64/libopencv_dnn.so
/usr/lib64/libopencv_features2d.so
/usr/lib64/libopencv_flann.so
/usr/lib64/libopencv_highgui.so
/usr/lib64/libopencv_imgcodecs.so
/usr/lib64/libopencv_imgproc.so
/usr/lib64/libopencv_ml.so
/usr/lib64/libopencv_objdetect.so
/usr/lib64/libopencv_photo.so
/usr/lib64/libopencv_stitching.so
/usr/lib64/libopencv_video.so
/usr/lib64/libopencv_videoio.so
/usr/lib64/pkgconfig/opencv.pc
/usr/lib64/pkgconfig/opencv4.pc

%files extras-testing
%defattr(-,root,root,-)
/usr/bin/haswell/avx512_1/opencv_perf_calib3d
/usr/bin/haswell/avx512_1/opencv_perf_core
/usr/bin/haswell/avx512_1/opencv_perf_dnn
/usr/bin/haswell/avx512_1/opencv_perf_features2d
/usr/bin/haswell/avx512_1/opencv_perf_imgcodecs
/usr/bin/haswell/avx512_1/opencv_perf_imgproc
/usr/bin/haswell/avx512_1/opencv_perf_objdetect
/usr/bin/haswell/avx512_1/opencv_perf_photo
/usr/bin/haswell/avx512_1/opencv_perf_stitching
/usr/bin/haswell/avx512_1/opencv_perf_video
/usr/bin/haswell/avx512_1/opencv_perf_videoio
/usr/bin/haswell/avx512_1/opencv_test_calib3d
/usr/bin/haswell/avx512_1/opencv_test_core
/usr/bin/haswell/avx512_1/opencv_test_dnn
/usr/bin/haswell/avx512_1/opencv_test_features2d
/usr/bin/haswell/avx512_1/opencv_test_flann
/usr/bin/haswell/avx512_1/opencv_test_highgui
/usr/bin/haswell/avx512_1/opencv_test_imgcodecs
/usr/bin/haswell/avx512_1/opencv_test_imgproc
/usr/bin/haswell/avx512_1/opencv_test_ml
/usr/bin/haswell/avx512_1/opencv_test_objdetect
/usr/bin/haswell/avx512_1/opencv_test_photo
/usr/bin/haswell/avx512_1/opencv_test_stitching
/usr/bin/haswell/avx512_1/opencv_test_video
/usr/bin/haswell/avx512_1/opencv_test_videoio
/usr/bin/haswell/opencv_perf_calib3d
/usr/bin/haswell/opencv_perf_core
/usr/bin/haswell/opencv_perf_dnn
/usr/bin/haswell/opencv_perf_features2d
/usr/bin/haswell/opencv_perf_imgcodecs
/usr/bin/haswell/opencv_perf_imgproc
/usr/bin/haswell/opencv_perf_objdetect
/usr/bin/haswell/opencv_perf_photo
/usr/bin/haswell/opencv_perf_stitching
/usr/bin/haswell/opencv_perf_video
/usr/bin/haswell/opencv_perf_videoio
/usr/bin/haswell/opencv_test_calib3d
/usr/bin/haswell/opencv_test_core
/usr/bin/haswell/opencv_test_dnn
/usr/bin/haswell/opencv_test_features2d
/usr/bin/haswell/opencv_test_flann
/usr/bin/haswell/opencv_test_highgui
/usr/bin/haswell/opencv_test_imgcodecs
/usr/bin/haswell/opencv_test_imgproc
/usr/bin/haswell/opencv_test_ml
/usr/bin/haswell/opencv_test_objdetect
/usr/bin/haswell/opencv_test_photo
/usr/bin/haswell/opencv_test_stitching
/usr/bin/haswell/opencv_test_video
/usr/bin/haswell/opencv_test_videoio
/usr/bin/opencv_perf_calib3d
/usr/bin/opencv_perf_core
/usr/bin/opencv_perf_dnn
/usr/bin/opencv_perf_features2d
/usr/bin/opencv_perf_imgcodecs
/usr/bin/opencv_perf_imgproc
/usr/bin/opencv_perf_objdetect
/usr/bin/opencv_perf_photo
/usr/bin/opencv_perf_stitching
/usr/bin/opencv_perf_video
/usr/bin/opencv_perf_videoio
/usr/bin/opencv_test_calib3d
/usr/bin/opencv_test_core
/usr/bin/opencv_test_dnn
/usr/bin/opencv_test_features2d
/usr/bin/opencv_test_flann
/usr/bin/opencv_test_highgui
/usr/bin/opencv_test_imgcodecs
/usr/bin/opencv_test_imgproc
/usr/bin/opencv_test_ml
/usr/bin/opencv_test_objdetect
/usr/bin/opencv_test_photo
/usr/bin/opencv_test_stitching
/usr/bin/opencv_test_video
/usr/bin/opencv_test_videoio

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/avx512_1/libopencv_calib3d.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_calib3d.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_core.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_core.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_dnn.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_dnn.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_features2d.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_features2d.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_flann.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_flann.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_imgcodecs.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_imgcodecs.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_imgproc.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_imgproc.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_ml.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_ml.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_objdetect.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_objdetect.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_photo.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_photo.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_stitching.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_stitching.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_video.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_video.so.4.4.0
/usr/lib64/haswell/avx512_1/libopencv_videoio.so.4.4
/usr/lib64/haswell/avx512_1/libopencv_videoio.so.4.4.0
/usr/lib64/haswell/libopencv_calib3d.so.4.4
/usr/lib64/haswell/libopencv_calib3d.so.4.4.0
/usr/lib64/haswell/libopencv_core.so.4.4
/usr/lib64/haswell/libopencv_core.so.4.4.0
/usr/lib64/haswell/libopencv_dnn.so.4.4
/usr/lib64/haswell/libopencv_dnn.so.4.4.0
/usr/lib64/haswell/libopencv_features2d.so.4.4
/usr/lib64/haswell/libopencv_features2d.so.4.4.0
/usr/lib64/haswell/libopencv_flann.so.4.4
/usr/lib64/haswell/libopencv_flann.so.4.4.0
/usr/lib64/haswell/libopencv_highgui.so.4.4
/usr/lib64/haswell/libopencv_highgui.so.4.4.0
/usr/lib64/haswell/libopencv_imgcodecs.so.4.4
/usr/lib64/haswell/libopencv_imgcodecs.so.4.4.0
/usr/lib64/haswell/libopencv_imgproc.so.4.4
/usr/lib64/haswell/libopencv_imgproc.so.4.4.0
/usr/lib64/haswell/libopencv_ml.so.4.4
/usr/lib64/haswell/libopencv_ml.so.4.4.0
/usr/lib64/haswell/libopencv_objdetect.so.4.4
/usr/lib64/haswell/libopencv_objdetect.so.4.4.0
/usr/lib64/haswell/libopencv_photo.so.4.4
/usr/lib64/haswell/libopencv_photo.so.4.4.0
/usr/lib64/haswell/libopencv_stitching.so.4.4
/usr/lib64/haswell/libopencv_stitching.so.4.4.0
/usr/lib64/haswell/libopencv_video.so.4.4
/usr/lib64/haswell/libopencv_video.so.4.4.0
/usr/lib64/haswell/libopencv_videoio.so.4.4
/usr/lib64/haswell/libopencv_videoio.so.4.4.0
/usr/lib64/libopencv_calib3d.so.4.4
/usr/lib64/libopencv_calib3d.so.4.4.0
/usr/lib64/libopencv_core.so.4.4
/usr/lib64/libopencv_core.so.4.4.0
/usr/lib64/libopencv_dnn.so.4.4
/usr/lib64/libopencv_dnn.so.4.4.0
/usr/lib64/libopencv_features2d.so.4.4
/usr/lib64/libopencv_features2d.so.4.4.0
/usr/lib64/libopencv_flann.so.4.4
/usr/lib64/libopencv_flann.so.4.4.0
/usr/lib64/libopencv_highgui.so.4.4
/usr/lib64/libopencv_highgui.so.4.4.0
/usr/lib64/libopencv_imgcodecs.so.4.4
/usr/lib64/libopencv_imgcodecs.so.4.4.0
/usr/lib64/libopencv_imgproc.so.4.4
/usr/lib64/libopencv_imgproc.so.4.4.0
/usr/lib64/libopencv_ml.so.4.4
/usr/lib64/libopencv_ml.so.4.4.0
/usr/lib64/libopencv_objdetect.so.4.4
/usr/lib64/libopencv_objdetect.so.4.4.0
/usr/lib64/libopencv_photo.so.4.4
/usr/lib64/libopencv_photo.so.4.4.0
/usr/lib64/libopencv_stitching.so.4.4
/usr/lib64/libopencv_stitching.so.4.4.0
/usr/lib64/libopencv_video.so.4.4
/usr/lib64/libopencv_video.so.4.4.0
/usr/lib64/libopencv_videoio.so.4.4
/usr/lib64/libopencv_videoio.so.4.4.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/opencv/0aacebb8a54d52a40db8d2d449eceb42f66e198b
/usr/share/package-licenses/opencv/13afd4683100a8df1656137a1957db39e9f6f3bf
/usr/share/package-licenses/opencv/14b5d0210560128e1a5d5204698cf705011ef792
/usr/share/package-licenses/opencv/49709bd29acf27e87953e37e63bb68373347a805
/usr/share/package-licenses/opencv/4f83a9480069279bc79a7af6990b9a546a1d0c02
/usr/share/package-licenses/opencv/59cd938fcbd6735b1ef91781280d6eb6c4b7c5d9
/usr/share/package-licenses/opencv/7235f6784b4eae4c40a259dcecc7a20e6c487263
/usr/share/package-licenses/opencv/72f59fbac43fa1a7f0607d7fdba747832e626656
/usr/share/package-licenses/opencv/91a334a8403de4f677844cfcf4067720be0bb802
/usr/share/package-licenses/opencv/99d45ca0d503d7988a486e0d4f95058f89e14115
/usr/share/package-licenses/opencv/a0bcc878d7e7181b120ae51837c8d1703fe919ab
/usr/share/package-licenses/opencv/a2f64f2a85f5fd34bda8eb713c3aad008adbb589
/usr/share/package-licenses/opencv/a5f4d6f407de11b9ce0fef27e335ddcaeded9f2d
/usr/share/package-licenses/opencv/a6c8c1690157753de298c1ea2a66a2400d1ab5a3
/usr/share/package-licenses/opencv/eaa22397809541edc6c7678716c4929f4977ee32
/usr/share/package-licenses/opencv/ec4468ecfe59c46406d4fc5aca1cee2a83c4d93e
/usr/share/package-licenses/opencv/fc3951ba26fe1914759f605696a1d23e3b41766f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
